// @flow

import React from 'react';
import './reset.css';
import styled from 'styled-components';

// Components
import Page from '../components/pageTracked';
import Seo from '../components/seo';

const Wrapper = styled.div`
  td {
    width: 50%;
    padding: 20px;
  }
`;

const privacy = () => (
  <>
    <Seo title="Privacy policy" />
    <Page title="Privacy policy">
      <Wrapper>
        <p>Welcome to the Privacy Policy of Kiwi.com Events and Community.</p>
        <p>
          If you are reading this, one of two scenarios happened: A) You’re
          either thinking about attending, are attending, or have attended one
          of the events that we organise or B) we found you on the internet and
          think that you might be interested in Kiwi.com events, job offers or
          other messages according to your skills and interests.
        </p>
        <p>
          For the purposes of organising our events and to be able to keep in
          touch with you with our job offers and other relevant information, we
          need to process your Personal Data. In this Privacy Policy, we explain
          exactly why and how we do that and provide you with other important
          information which you need so that you always remain in control of
          your privacy.
        </p>
        <h3>A. WHO ARE WE AND HOW CAN YOU CONTACT US?</h3>
        <p>
          We, as the Data Controller, are the company <b>Kiwi.com s.r.o.</b>, ID
          No. 29352886, with a registered office at Palachovo náměstí 797/4,
          Starý Lískovec, Post Code 625 00 Brno, registered in the Companies
          Register administered by the Regional Court of Brno, file no. C 74565,
          Tax ID No. CZ29352886.
        </p>
        <p>
          <strong>
            For all matters concerning privacy and data protection, you can
            always contact us via email privacy-community@kiwi.com.
          </strong>
        </p>
        <h3>B. SOME TERMS THAT WE USE IN THIS PRIVACY POLICY</h3>
        <p>
          <b>Personal Data:</b> any information relating to a directly or
          indirectly identified or identifiable natural person. That means that
          if we possess means to identify either you or even the device you’re
          using, any information that we can connect to you will be treated as
          Personal Data.
        </p>
        <p>
          <b>Data Controller:</b> someone that determines the purposes and means
          of processing Personal Data. For example, we are a Data Controller
          when we process your Personal Data for the purposes stated in this
          Privacy Policy. Each Data Controller (to whom the GDPR or similar
          legal regime applies) should have a Privacy Policy such as this one
          where you can learn about how your Personal Data is processed. You can
          see the full list of Data Controllers we might share the data with
          below.{' '}
        </p>
        <p>
          <b>Data Processor:</b> a third party that only helps to achieve the
          purposes determined by the Data Controller. For example, we as a Data
          Controller use many third-party services to which we outsource some
          parts of our activities that we don’t do ourselves for various reasons
          such as cost efficiency. A Data Processor is only allowed to process
          your Personal Data according to our documented instructions, and the
          GDPR obliges us to have a strict formal contractual relationship that
          ensures a truly sufficient protection of your privacy.
        </p>
        <p>
          <b>Third Countries:</b> countries in which the GDPR regime is not
          applicable. Currently, by Third Countries we mean all countries that
          lie outside of the European Union.
        </p>
        <h2>C. PARTICIPANTS OF THE KIWI.COM EVENTS</h2>
        <p>
          We process your Personal Data to be able to organise the event, to
          improve our ability to organise other events, and for the promotional
          purposes of Kiwi.com in connection to this event or future events. In
          this Privacy Policy, you will learn how and why we use your Personal
          Data and with whom we might share it.
        </p>
        <h3>C.1 WHAT PERSONAL DATA WE PROCESS AND WHERE DO WE GET IT?</h3>
        <p>We process the following categories of your Personal Data:</p>
        <ol type="a">
          <li>identification information (Name and Surname),</li>
          <li>contact details (e-mail),</li>
          <li>
            your professional information (work experience, education, skills,
            languages, interests,...),
          </li>
          <li>hyperlinks to your social media profiles, and</li>
          <li>information generated by your activity or our staff.</li>
        </ol>
        <p>
          The identification information and contact details we obtained
          directly from you, the professional information is downloaded by our
          CRM (Beamery) from the social media profiles such as LinkedIn or
          GitHub which were linkable to the contact details that you have
          provided to us. The rest of the data is generated either by your
          activity (e.g. log about unsubscription from a newsletter) or by our
          employees (we might assign you a tag to sort you into some category
          because we think that you’d be interested in a specific type of
          content).
        </p>
        <h3>C.1 FOR WHAT PURPOSES DO WE USE YOUR PERSONAL DATA?</h3>
        <h4>C.1.I Organisation of the event</h4>
        <p>
          The main and most important purpose for which we need to process your
          Personal Data is the organisation of the event itself. The processing
          of Personal Data for this purpose includes processing of your
          applications, administration of the list of participants, and other
          necessary activities. This processing is done on the basis of the
          fulfilment of an agreement. In many cases, we don’t actually conclude
          any formal contract but there is an implicit non-verbal agreement
          which is concluded between our participants and us when we accept
          their application.
        </p>
        <h4>C.1.II Improving our ability to organise events</h4>
        <p>
          We would also like to process your Personal Data for the purpose of
          improving our ability to organise events. After the event, we might
          send you a feedback form where we ask you for your opinion regarding
          your experience at the event. Completion of the feedback form is
          voluntary. We will only process your Personal Data for this purpose if
          you give us your consent through the feedback form. You may always
          revoke your consent by getting in touch with us at
          privacy-community@kiwi.com.
        </p>
        <h4>C.1.III Promotional purposes</h4>
        <p>
          Another purpose for which we might use your Personal Data (such as
          photos or videos where you appear) is the promotion of the event on
          which you participated and similar events in the future. We usually
          promote our events through our social media accounts, through our
          YouTube channel, through our newsletter and through paid adverts. This
          processing is done based on our legitimate interest of direct
          marketing. If you don’t want us to process your Personal Data for this
          purpose, you may always object to it by writing us an email at
          privacy-community@kiwi.com.
        </p>
        <h4>C.1.IV Information about future events and job offers</h4>
        <p>
          On the application form for any of our events, you may also choose to
          subscribe to our newsletters through which you can keep in touch with
          our future events and possible job offers according to your skills and
          interests. In case you do, you will become a part of the Kiwi.com
          Community. For such cases, see the relevant information below.
        </p>
        <h2>D. MEMBERS OF KIWI.COM COMMUNITY</h2>
        <p>
          If you applied for one of our events or if we found you on the
          internet and found you interesting, you were given the choice of
          becoming a member of the Kiwi.com Community. In this section of our
          Privacy Policy, we explain the purposes for which we need to process
          the Personal Data of our members.
        </p>
        <h3>D.1 WHAT PERSONAL DATA WE PROCESS AND WHERE DO WE GET IT?</h3>
        <p>We process the following categories of your Personal Data:</p>
        <ol type="a">
          <li>identification information (Name and Surname),</li>
          <li>contact details (e-mail),</li>
          <li>
            your professional information (work experience, education, skills,
            languages, interests,...),
          </li>
          <li>hyperlinks to your social media profiles, and</li>
          <li>information generated by your activity or our staff.</li>
        </ol>
        <p>
          The identification information and contact details we obtained
          directly from you, the professional information is downloaded by our
          CRM (Beamery) from the social media profiles such as LinkedIn or
          GitHub which were linkable to the contact details that you have
          provided to us. The rest of the data is generated either by your
          activity (e.g. log about unsubscription from a newsletter) or by our
          employees (we might assign you a tag to sort you into some category
          because we think that you’d be interested in a specific type of
          content).
        </p>
        <h3>D.2 FOR WHAT PURPOSES DO WE USE YOUR PERSONAL DATA?</h3>
        <h3>D.2.I Getting in touch</h3>
        <p>
          If we found you on the internet and sent you the invitation link, we
          processed your Personal Data even before you had a chance to give us
          your consent. Our recruiters actively browse through social media
          sites such as GitHub or Linkedin and look for interesting people who
          might be interested in working for Kiwi.com. Once they find the right
          people, they import some information about these individuals into our
          tool (Beamery) which then enriches their profile with data from around
          the internet and sends them a link to a consent form where we ask
          whether they would like to become a part of the Kiwi.com Community.
          From the point where we initially collect the data, we keep it for 30
          days. If the approached person doesn’t give us the consent within this
          period, the data is automatically deleted. We process the Personal
          Data for this purpose based on the legal grounds of legitimate
          interest.
        </p>
        <h3>D.2.II Newsletter with future events and job offers at Kiwi.com</h3>
        <p>
          The whole point of being a member of the Kiwi.com Community is to stay
          up to date with the events which we organise, the most recent job
          offers and other interested stuff about our company.
        </p>
        <p>
          If you are offered to become a member of the Kiwi.com Community on
          your application form for any of our events, you can choose which
          types of messages you would like to be receiving and which not. If you
          want to just go to the event and don’t want to receive any messages,
          simply don’t check any of the checkboxes and your Personal Data will
          be deleted automatically after the event you’re applying for ends.
        </p>
        <p>
          If we found you on the internet and asked you for a consent to become
          a member of the Kiwi.com Community via email, in case you give us the
          consent, we’ll automatically subscribe you to the invitations to our
          events and to job offers. You can always change this by unsubscribing
          through a link which you’ll find in every email that you’ll receive
          from us.
        </p>
        <p>
          Kiwi.com is a large company and almost all skill sets have some
          application here. However, we don’t want to spam our community members
          with messages which they aren’t interested in. Therefore, we use the
          information that we collect from the social media profiles to send
          invitations to our events, job offers and other messages tailored
          according to the skill set and interests of every individual member.
          This is done through a tool called Beamery. We create a profile for
          you within this tool and it automatically finds your profiles based on
          your email address. It then downloads information such as your work
          experience, education, skills, languages and interests and
          periodically updates them. Based on this data, we can sort you into
          specific categories and send you content which we think you’ll be most
          interested in.
        </p>
        <p>
          From the moment you give us your consent, we will retain your Personal
          Data for 3 years. Afterwards, we will ask you for your confirmation,
          whether you’d like to stay engaged, and unless you give us your
          consent, we will delete all your Personal Data.
        </p>
        <h2>E. WHO DO WE SHARE YOUR PERSONAL DATA WITH AND WHY?</h2>
        <h3>E.1 SHARING DATA WITH OTHER DATA CONTROLLERS</h3>
        <p>
          In some cases, we will share your Personal Data with third parties for
          their purposes. Each third party controller will treat your Personal
          Data in accordance with their own Privacy Policy (which is published
          on their website). Disclosure of Personal Data to other service
          providers will be done in accordance with the applicable Personal Data
          laws and regulations.
        </p>
        <table>
          <tr>
            <th>PURPOSE</th>
            <th>PARTNERS</th>
          </tr>
          <tr>
            <td>
              <b>Promotion</b>
              <br /> We use these partners for the promotion of the events you
              participated in and similar future events. If you haven’t
              participated in any of our event, this doesn’t apply to you.
            </td>
            <td>
              Social media sites <br />
              Digital news media outlets
            </td>
          </tr>
        </table>
        <h3>E.2 SHARING DATA WITH DATA PROCESSORS</h3>
        <p>
          In order to do our work in the most effective way, we use many tools
          and apps which help us. The providers of such tools are third-parties
          so technically, the Personal Data is sent to other companies and we
          need to inform you about such transfers. However, in such cases, these
          third parties are acting on our behalf as our Data Processors and we
          always stay in control of your Personal Data. That means that even
          though the Data Processors are in possession of your data, they can
          only process it for our purposes and we are always in charge of it.
          They cannot under any circumstances use the data for their own
          purposes or use the data in a way that would go against our agreement.
          Furthermore, we only use partners that have given us sufficient
          guarantees that they comply with the GDPR requirements and that your
          data will always be kept safe.
        </p>
        <tr>
          <th>PURPOSE</th>
          <th>PARTNERS</th>
        </tr>
        <tr>
          <td>
            <b>Mailing tool</b>
            <br /> We use a mailing tool that enables us to efficiently
            administer our mailing database.
          </td>
          <td>Mailchimp (The Rocket Science Group LLC)</td>
        </tr>
        <tr>
          <td>
            <b>Event organisation platforms</b>
            <br /> For the purpose of the organisation of our events and their
            promotion, we use certain platforms to connect with our (potential)
            participants.
          </td>
          <td>
            EvenBrite.com (Eventbrite, Inc.) <br />
            Meetup.com (Meetup, Inc.)
          </td>
        </tr>
        <tr>
          <td>
            <b>Administration</b>
            <br /> We use a tool which allows us to manage a database of people
            interested in Kiwi.com and to send them invitations to our events
            and job offers.
          </td>
          <td>Beamery Ltd.</td>
        </tr>
        <tr>
          <td>
            <b>Evaluation of applicants</b>
            <br /> Sometimes, before we decide whether to choose a certain
            applicant for an Event, we give them a coding task that they need to
            solve beforehand. For this, we use a tool called Codility.
          </td>
          <td>Codility Ltd.</td>
        </tr>
        <h2>F. HOW LONG DO WE STORE YOUR PERSONAL DATA FOR?</h2>
        <p>
          In general, we will process your Personal Data until we won’t need it
          for any of these purposes defined in this Privacy Policy. The maximum
          length of processing is 3 years after the collection of the Personal
          Data (or more if you renew your consent after this initial period).
        </p>
        <h2>G. HOW TO ACCESS AND CONTROL YOUR PERSONAL DATA?</h2>
        <p>
          We want you to always be in control of your Personal Data. To this
          end, you have certain rights that allow for it. Under certain
          conditions, you may:
        </p>
        <ol type="a">
          <li>
            Gain access to all your data that we use or processing, and even get
            a copy of all of it
          </li>
          <li>Ask us to delete your data</li>
          <li>
            Correct the data that we are processing if you think that there are
            mistakes
          </li>
          <li>Restrict the processing of your data</li>
          <li>
            Receive your Personal Data in a commonly used and machine-readable
            format or to have this data transmitted to a different provider.
          </li>
        </ol>
        <p>
          You can exercise your rights by contacting us at
          privacy-community@kiwi.com.
        </p>
        <h2>I. TRANSFERRING YOUR DATA OUTSIDE OF THE EUROPEAN UNION</h2>
        <p>
          We will only transfer your Personal Data to Third Countries in cases
          where it is necessary given the residency of our Data Processor and
          the Data Controllers which are listed in this Privacy Policy. When
          transferring to countries without adequate regulations according to
          the Art. 45 GDPR, we will only do so after we obtain the necessary
          safeguards, specifically the Standard Contractual Clauses or Binding
          Corporate Rules.
        </p>
        <h2>J. COMPLAINT WITH THE SUPERVISORY AUTHORITY</h2>
        <p>
          Data Protection is a serious matter and the rules are quite difficult
          to implement correctly. No one is perfect, and it may happen that we
          make a mistake. If you feel that we mishandled your Personal Data,
          please turn to us first. We promise that we will try our best to
          resolve the situation. You can always approach us with any privacy or
          data protection related issue at privacy-community@kiwi.com.
        </p>
        <p>
          Nevertheless, at any time, you have the right to lodge a complaint
          with a supervisory authority. If you are from the EU, you can lodge a
          complaint at the authority in the member state of your residence, in
          the member state where you work or in the member state of the alleged
          infringement.
        </p>
        <p>
          Generally, the complaints will be handled by the Czech Office for
          Personal Data Protection. You can learn more at http://www.uoou.cz.
        </p>
      </Wrapper>
    </Page>
  </>
);

export default privacy;
